name: CI

on:
  push:
    branches:
      - main
      - test-ci-setup
  pull_request:
    branches:
      - main
      - test-ci-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Biome
        run: bun check

      - name: Build with Tsup
        run: bun run build

      - name: Run tests with coverage
        run: bun test

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage